name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["type: Bug", "state: Pending"]
assignees:
  - hoffstadt
body:
  - type: markdown
    attributes:
      value: |
        Any images or screenshots can be added in the comments.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: alleged-issue
    attributes:
      label: What is the issue?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce?
      description: Step by step instructions on how to reproduce
      value: "Steps to reproduce the behavior:"
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you running?
      multiple: true
      options:
        - All
        - Windows
        - Linux
        - MacOS
    validations:
      required: true
  - type: dropdown
    id: graphics-api
    attributes:
      label: Graphics Backend
      multiple: true
      options:
        - All
        - NA
        - Vulkan
        - Metal
        - Directx 11
        - Directx 12
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: dropdown
    id: system
    attributes:
      label: System
      options:
        - Core
        - OS
        - Drawing
        - User Interface
        - Logging
        - Profiling
        - Data structures
        - Memory
        - ECS
        - Job
        - Stats
        - Image
        - Allocators
        - Testing
        - Build
        - Graphics
        - Model Loader
        - Renderer
        - Shader
        - Resource
        - GPU Allocators
        - Libs
