name: Feature Request
description: File a feature request
title: "[FEATURE]: "
labels: ["type: Feature", "state: Pending"]
assignees:
  - hoffstadt
body:
  - type: markdown
    attributes:
      value: |
        Any images or screenshots can be added in the comments.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: alleged-feature
    attributes:
      label: What is the feature?
      description: Describe the feature
      value: "I would like x"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Desribe alternatives you have considered?
      description: A clear and concise description of any alternative solutions or features you have considered.
      value: "Other potential solutions"
    validations:
      required: true
  - type: dropdown
    id: extension
    attributes:
      label: Extension
      options:
        - New
        - Animation
        - BVH
        - Camera
        - Collision
        - Compression
        - Config
        - Console
        - Date Time
        - Draw Backend
        - Draw
        - ECS
        - ECS Tools
        - Gizmo
        - GPU Allocators
        - Graphics
        - Image
        - Job
        - Log
        - Mesh
        - Model Loader
        - Pak
        - Physics
        - Platform
        - Profile
        - Rect Pack
        - Renderer
        - Resource Manager
        - Screen Log
        - Shader
        - Shader Variant
        - Starter
        - Stats
        - String Intern
        - Terrain
        - Tools
        - UI
        - Virtual File System
  - type: dropdown
    id: libraries
    attributes:
      label: Libraries
      options:
        - New
        - pl_ds.h
        - pl_json.h
        - pl_log.h
        - pl_math.h
        - pl_memory.h
        - pl_profile.h
        - pl_stl.h
        - pl_string.h
        - pl_test.h
  - type: dropdown
    id: system
    attributes:
      label: System
      options:
        - New
        - Core Framework
        - Build System
        - Scripts
        - Examples
        - Window API
        - Library API
