#version 460
#extension GL_ARB_separate_shader_objects : enable

/*
   sky_multiscatter_lut.comp
*/

/*
Index of this file:
// [SECTION] notes
// [SECTION] includes
// [SECTION] defines
// [SECTION] bind groups
// [SECTION] entry
*/

//-----------------------------------------------------------------------------
// [SECTION] notes
//-----------------------------------------------------------------------------

/*
  - At this altitude, with the Sun at this zenith angle, how much atmospheric
    radiance comes from second- and higher-order scatter?
*/

//-----------------------------------------------------------------------------
// [SECTION] includes
//-----------------------------------------------------------------------------

#include "pl_sky.inc"
#include "pl_bg_scene.inc"

//-----------------------------------------------------------------------------
// [SECTION] defines
//-----------------------------------------------------------------------------

// #define approximation
#define PL_INNER_SAMPLE_COUNT 20

//-----------------------------------------------------------------------------
// [SECTION] bind groups
//-----------------------------------------------------------------------------

// bind group 1
layout(set = 1, binding = 0, r11f_g11f_b10f) uniform image2D multiscatterLut;
layout(set = 1, binding = 1) uniform texture2D transmissionLut;

//-----------------------------------------------------------------------------
// [SECTION] entry
//-----------------------------------------------------------------------------

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

void main()
{

    ivec2 uv = ivec2(gl_GlobalInvocationID.xy);

    if(any(greaterThanEqual(uv, imageSize(multiscatterLut))))
        return;

    float x = uv.x / float(imageSize(multiscatterLut).x); // altitude, height in atomosphere
    float y = uv.y / float(imageSize(multiscatterLut).y); // solar zenith angle

    float fHeight = mix(0, tGpuScene.tData.atmosphereHeight, x);
    vec3 P = vec3(0, fHeight + tGpuScene.tData.planetRadius, 0);
    vec3 tEarthCenter = vec3(0);

    float fUpDot = y * 2 - 1;
    fUpDot = max(fUpDot, -0.999); // problems with fUpDot == -1.0
    vec3 L = vec3(0, fUpDot, sqrt(1 - (fUpDot * fUpDot))); // direction towards sun

    vec3 L_2nd = vec3(0); // radiance available from second scattering order
    vec3 f_ms = vec3(0);  // fraction of light that may be scattered again

    float fIsotropicPhase = 1.0 / (4.0 * PL_PI);

    // sampling over sphere
    int iSampleCountSqrt = 8;
    float fSampleCountSqrtRcp = 1.0 / float(iSampleCountSqrt);
    for(int i = 0; i < iSampleCountSqrt; i++)
    {
        for(int j = 0; j < iSampleCountSqrt; j++)
        {

            float fTheta =     PL_PI * (float(i)) * fSampleCountSqrtRcp;
            float fPhi   = 2 * PL_PI * (float(j) + 0.5) * fSampleCountSqrtRcp;

            float fSinTheta = sin(fTheta);
            float fCosTheta = cos(fTheta);
            vec3 V = vec3(fSinTheta * cos(fPhi), fSinTheta, fSinTheta * sin(fPhi));

            vec3 inscattered = vec3(0.0);
            plIntersection intersection = pl_ray_intersection_planet(P, V, tEarthCenter, tGpuScene.tData.planetRadius, tGpuScene.tData.atmosphereHeight);
            vec3 tCurrentPosition = P;
            float fStepSize = intersection.fDistance / PL_INNER_SAMPLE_COUNT;
            V *= fStepSize;

            vec3 L_f = vec3(0.0);

            // estimates light reflected from planet surface if sampled direction hits the ground
            vec3 tEarthAlbedo = vec3(0.3);
            vec3 tEarthHitNormal = normalize(intersection.tPos - tEarthCenter);
            float fEarthNoL = clamp(dot(tEarthHitNormal, L), 0, 1);

            vec3 tUp = normalize(tCurrentPosition - tEarthCenter);
            vec2 lutUV = pl_compute_lut_uv(0, tGpuScene.tData.atmosphereHeight, tEarthHitNormal, L);
            vec3 transmissionToIntersection = texture(sampler2D(transmissionLut, tSamplerLinearClamp), lutUV).rgb;
            vec3 incomingLight = transmissionToIntersection;
            vec3 planetLit = tEarthAlbedo / PL_PI * incomingLight * fEarthNoL;
            vec3 direct = intersection.bHitEarth ? planetLit : vec3(0.0);

            vec3 transmission = vec3(1.0);

            
            //assumes height and tUp vector is constant, allows sun transmission LUT lookup to be pulled out of loop
            #ifdef approximation
            float currentHeight = -tCurrentPosition.y - tGpuScene.tData.planetRadius;
            #endif

            for(int k = 0; k < PL_INNER_SAMPLE_COUNT; k++)
            {

                tCurrentPosition += V;

                vec3 tUp;
                
                #ifdef approximation
                tUp = vec3(0, 1, 0);
                float currentHeight = fHeight
                #else
                tUp = tCurrentPosition - tEarthCenter;
                float tUpLength = length(tUp);
                float currentHeight = tUpLength - tGpuScene.tData.planetRadius;
                tUp /= tUpLength;
                #endif

                plAtmosphereCoefficients tCoefficients = pl_calculate_coefficients(currentHeight, tGpuScene.tData);
                vec3 tScatteringCo = tCoefficients.tScatterRayleigh + tCoefficients.tScatterMie;

                // light arriving at point
                vec2 lutUV = pl_compute_lut_uv(currentHeight, tGpuScene.tData.atmosphereHeight, tUp, L);
                vec3 transmissionSun = texture(sampler2D(transmissionLut, tSamplerLinearClamp), lutUV).rgb;

                // inscattering from light at point
                vec3 coefficientIntegral = pl_integrate_inscattering(tScatteringCo, tCoefficients.tExtinction, fStepSize);
                L_f += coefficientIntegral * transmission;

                // reuse result integration as integration is linear in factor
                vec3 scatterIntegral = coefficientIntegral * transmissionSun * fIsotropicPhase;
                inscattered = inscattered + scatterIntegral * transmission;

                transmission *= exp(-tCoefficients.tExtinction * fStepSize);
            }

            f_ms += L_f * fSinTheta;  // isotropic phase function reduced with integral over sphere(factor 4 x pi)
            L_2nd += (direct * transmission + inscattered) * fSinTheta; // isotropic phase function reduced with integral over sphere(factor 4 x pi)
        }
    }

    float sampleCountInverse = 1.0 / (iSampleCountSqrt * iSampleCountSqrt);
    f_ms *= sampleCountInverse;
    L_2nd *= sampleCountInverse;

    vec3 F_ms = vec3(1.0) / (1.0 - f_ms);
    vec3 multiscatter = L_2nd * F_ms;
    imageStore(multiscatterLut, uv, vec4(multiscatter, 0.0));
}