#version 450
#extension GL_ARB_separate_shader_objects : enable

/*
   pl_sky_transmission_lut.comp
*/

/*
Index of this file:
// [SECTION] notes
// [SECTION] includes
// [SECTION] defines
// [SECTION] bind groups
// [SECTION] entry
*/

//-----------------------------------------------------------------------------
// [SECTION] notes
//-----------------------------------------------------------------------------

/*
 - If i start at altitude h and look in direction V, how much light survives
   traveling through the atmosphere before it exits or hits the ground. The LUT
   stores an RGB transmittance value so later shaders can sample instead of ray
   marching every time.
*/

//-----------------------------------------------------------------------------
// [SECTION] includes
//-----------------------------------------------------------------------------

#include "pl_sky.inc"
#include "pl_bg_scene.inc"

//-----------------------------------------------------------------------------
// [SECTION] defines
//-----------------------------------------------------------------------------

#define PL_SAMPLE_COUNT 40

//-----------------------------------------------------------------------------
// [SECTION] bind groups
//-----------------------------------------------------------------------------

// bind group 1
layout(set = 1, binding = 0, r11f_g11f_b10f) uniform image2D outputImage;

//-----------------------------------------------------------------------------
// [SECTION] entry
//-----------------------------------------------------------------------------

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

void main() 
{

    ivec2 uv = ivec2(gl_GlobalInvocationID.xy);

    if(any(greaterThanEqual(uv, imageSize(outputImage))))
        return;

    float x = uv.x / float(imageSize(outputImage).x - 1); // height in atmosphere
    float y = uv.y / float(imageSize(outputImage).y - 1); // direction relative to "up"

    // height 0 -> ground
    // height 1 -> top of atmosphere
    float fHeight = mix(0, tGpuScene.tData.atmosphereHeight, x);

    float fUpDot = y * 2.0 - 1.0; // basically dot(up, V)
    fUpDot = max(fUpDot, -0.999); // problems with fUpDot == -1.0

    // view direction (constructed such that the dot product with local up
    // equals fUpDot)
    vec3 V = vec3(0, fUpDot, sqrt(1 - (fUpDot * fUpDot))); // assuming spherical symmetry

    vec3 P = vec3(0, fHeight + tGpuScene.tData.planetRadius, 0);
    vec3 tEarthCenter = vec3(0);

    vec3 localUp =
        normalize(P - tEarthCenter);

    // find intersection with ground or atmosphere boundary (TODO: remove 0.01 properly)
    plIntersection tIntersection = pl_ray_intersection_planet(P + localUp * 0.01, V, tEarthCenter, tGpuScene.tData.planetRadius, tGpuScene.tData.atmosphereHeight);
    float fPathLength = max(distance(tIntersection.tPos, P), 0.01); //avoid division trough zero at atmosphere top

    // ray march and calculate attenuation through the atmosphere

    float fStepLength = fPathLength / PL_SAMPLE_COUNT;

    vec3 tCurrentPos = P;
    vec3 tTransmittance = vec3(1); // starts at 100% of light survives so far
    vec3 tStep = V * fStepLength;

    for(int i = 0; i < PL_SAMPLE_COUNT; i++)
    {
        tCurrentPos += tStep;

        float fCurrentHeight = max(distance(tEarthCenter, tCurrentPos) - tGpuScene.tData.planetRadius, 0);
        plAtmosphereCoefficients tCoefficients = pl_calculate_coefficients(fCurrentHeight, tGpuScene.tData);

        // Beer's law
        tTransmittance *= exp(-tCoefficients.tExtinction * fStepLength);
    }
    tTransmittance = tIntersection.bHitEarth ? vec3(0) : tTransmittance;
    imageStore(outputImage, uv, vec4(tTransmittance, 0.f));
}