#version 450
#extension GL_ARB_separate_shader_objects : enable

/*
   postprocess.comp
*/

/*
Index of this file:
// [SECTION] includes
// [SECTION] bind groups
// [SECTION] entry
*/

//-----------------------------------------------------------------------------
// [SECTION] includes
//-----------------------------------------------------------------------------

#include "pl_sky.inc"
#include "pl_bg_scene.inc"
#include "pl_bg_view.inc"

//-----------------------------------------------------------------------------
// [SECTION] bind groups
//-----------------------------------------------------------------------------

// bind group 0 (global)
// layout(set = 0, binding = 0) readonly uniform _plAtmosphereSettings { plAtmosphereSettings tData; } tAtmosphereSettings;
// layout(set = 0, binding = 1)  uniform sampler tSamplerLinearClamp;
// layout(set = 0, binding = 2)  uniform sampler tSamplerNearestClamp;

// bind group 2
layout(set = 2, binding = 0, rgba16f) uniform image2D tColorImage;
layout(set = 2, binding = 1) uniform texture2D tDepthImage;
layout(set = 2, binding = 2) uniform texture3D aerialPerspectiveLut;

//-----------------------------------------------------------------------------
// [SECTION] dynamic bind group
//-----------------------------------------------------------------------------

layout(set = 3, binding = 0) uniform PL_DYNAMIC_DATA
{
    uint uCameraIndex;
} tObjectInfo;

//-----------------------------------------------------------------------------
// [SECTION] entry
//-----------------------------------------------------------------------------

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

void main() 
{
    ivec2 tOutputSize = imageSize(tColorImage);
    ivec2 tPixel = ivec2(gl_GlobalInvocationID.xy);

    if(any(greaterThanEqual(tPixel, tOutputSize)))
        return;

    vec2 tTargetUV = (vec2(tPixel) + vec2(0.5)) / tOutputSize;
    vec2 tAerialLutUV = (vec2(tPixel) + vec2(0.5)) / tViewInfo.tData.tViewportSize.xy;
    // vec2 tAerialLutUV = tTargetUV;
    
    float depth = textureLod(sampler2D(tDepthImage, tSamplerNearestClamp), tTargetUV, 0.0).r;

    bool hasGeometry = depth > 1e-7;
    vec3 cameraPos = tViewInfo.tData.tCameraPos.xyz;
    float rayDistanceWorld;
    float aerialMaxDistanceAtmosphere = tGpuScene.tData.tAerialInfo.x;
    ivec3 aerialLutSize = textureSize(sampler3D(aerialPerspectiveLut, tSamplerNearestClamp), 0);

    if(hasGeometry)
    {
        vec3 ndcSpace = vec3(tTargetUV, depth);

        vec3 clipSpace = ndcSpace;
        clipSpace.xy = clipSpace.xy * 2.0 - 1.0;

        vec4 homoLocation = tViewInfo.tData.tCameraProjectionInv[tObjectInfo.uCameraIndex] * vec4(clipSpace, 1.0);
        vec4 tViewPosition = homoLocation; // homo location
        tViewPosition.xyz = tViewPosition.xyz / tViewPosition.w;
        tViewPosition.w = 1.0;
        vec4 tWorldPosition = tViewInfo.tData.tCameraViewInv[tObjectInfo.uCameraIndex] * tViewPosition;

        rayDistanceWorld = length(tWorldPosition.xyz - cameraPos);
    }
    else
    {
        rayDistanceWorld = tGpuScene.tData.tAerialInfo.x / tGpuScene.tData.fAtmosphereConversion;
    }

    float distanceAtmosphere = rayDistanceWorld * tGpuScene.tData.fAtmosphereConversion;

    float normalizedDistance = clamp(distanceAtmosphere / aerialMaxDistanceAtmosphere, 0.0, 1.0);

    float boundaryU = pow( normalizedDistance, 1.0 / tGpuScene.tData.tAerialInfo.y);

    float aerialZ = boundaryU - 0.5 / float(aerialLutSize.z);

    aerialZ = clamp(aerialZ, 0.5 / float(aerialLutSize.z), 1.0 - 0.5 / float(aerialLutSize.z));

    vec3 aerialUV = vec3(tAerialLutUV, aerialZ);

    vec4 aerial = textureLod(sampler3D(aerialPerspectiveLut, tSamplerLinearClamp), aerialUV, 0.0);
    float firstSliceBlend = clamp(boundaryU * float(aerialLutSize.z), 0.0, 1.0);
    aerial = mix(vec4(0.0, 0.0, 0.0, 1.0), aerial, firstSliceBlend);

    vec4 tOriginalColor = imageLoad(tColorImage, tPixel);
    tOriginalColor.rgb = tOriginalColor.rgb * aerial.a + aerial.rgb;
    imageStore(tColorImage, tPixel, tOriginalColor);
    // imageStore(tColorImage, tPixel, vec4(aerial.rgb * 10.0, 1.0));

}