#version 450
#extension GL_EXT_scalar_block_layout : enable

#include "pl_shader_interop_renderer.h"

//-----------------------------------------------------------------------------
// [SECTION] bind group 0
//-----------------------------------------------------------------------------

layout(std140, set = 0, binding = 0) buffer _tDataBuffer
{
	vec4 atVertexData[];
} tDataBuffer;

layout(scalar, set = 0, binding = 1) buffer _tOutputPosBuffer
{
	vec3 atVertexData[];
} tOutputPosBuffer;

layout(set = 0, binding = 2) uniform sampler tSampler;

//-----------------------------------------------------------------------------
// [SECTION] bind group 1
//-----------------------------------------------------------------------------

layout(std140, set = 1, binding = 0) readonly buffer _tSkinningData
{
	mat4 atData[];
} tSkinningData;

//-----------------------------------------------------------------------------
// [SECTION] dynamic bind group
//-----------------------------------------------------------------------------

layout(set = 3, binding = 0) uniform PL_DYNAMIC_DATA
{
    plGpuDynSkinData tData;
} tObjectInfo;

//-----------------------------------------------------------------------------
// [SECTION] helpers
//-----------------------------------------------------------------------------

mat4
get_matrix_from_texture(int index)
{
    return tSkinningData.atData[index + tObjectInfo.tData.uMatrixOffset];
}

mat4
get_skinning_matrix(vec4 inJoints0, vec4 inWeights0)
{
    mat4 skin = mat4(0);

    skin +=
        inWeights0.x * get_matrix_from_texture(int(inJoints0.x) * 2) +
        inWeights0.y * get_matrix_from_texture(int(inJoints0.y) * 2) +
        inWeights0.z * get_matrix_from_texture(int(inJoints0.z) * 2) +
        inWeights0.w * get_matrix_from_texture(int(inJoints0.w) * 2);

    if (skin == mat4(0)) { 
        return mat4(1); 
    }
    return skin;
}

//-----------------------------------------------------------------------------
// [SECTION] entry
//-----------------------------------------------------------------------------

layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

void
main()
{
    const int iSourceDataStride = 5;
    const int iDestDataStride = 4;

    const uint iVertexIndex = gl_WorkGroupID.x * 64 + gl_LocalInvocationID.x;

    if(iVertexIndex >= tObjectInfo.tData.uMaxSize)
        return;


    const uint iSourceVertexDataOffset = iSourceDataStride * iVertexIndex + tObjectInfo.tData.iSourceDataOffset;

    vec4 inPosition  = vec4(tDataBuffer.atVertexData[iSourceVertexDataOffset + 0].xyz, 1.0);
    vec3 inNormal    = tDataBuffer.atVertexData[iSourceVertexDataOffset + 1].xyz;
    vec4 inTangent   = tDataBuffer.atVertexData[iSourceVertexDataOffset + 2];
    vec4 inJoints0   = tDataBuffer.atVertexData[iSourceVertexDataOffset + 3];
    vec4 inWeights0  = tDataBuffer.atVertexData[iSourceVertexDataOffset + 4];

    mat4 skin = get_skinning_matrix(inJoints0, inWeights0);

    vec4 outPosition = skin * inPosition;
    vec3 outNormal = normalize(mat3(skin) * inNormal);
    vec3 outTangent = normalize(mat3(skin) * inTangent.xyz);

    const uint iDestVertexDataOffset = iDestDataStride * iVertexIndex + tObjectInfo.tData.iDestDataOffset;
    tOutputPosBuffer.atVertexData[iVertexIndex + tObjectInfo.tData.iDestVertexOffset] = outPosition.xyz;

    tDataBuffer.atVertexData[iDestVertexDataOffset + 0].xyz = outNormal;
    tDataBuffer.atVertexData[iDestVertexDataOffset + 1].xyz = outTangent;
}