
:: Project: pilotlight
:: Auto Generated by:
:: "pl_build.py" version: 1.1.0

:: Project: pilotlight

:: ################################################################################
:: #                              Development Setup                               #
:: ################################################################################

:: keep environment variables modifications local
@setlocal

:: make script directory CWD
@pushd %~dp0
@set dir=%~dp0

:: modify PATH to find vcvarsall.bat
@if exist "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2019/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2022/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2022/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build;%PATH%
@if exist "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build" @set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build;%PATH%

:: setup environment for MSVC dev tools
@call vcvarsall.bat amd64 > nul

:: default compilation result
@set PL_RESULT=[1m[92mSuccessful.[0m

:: default configuration
@set PL_CONFIG=debug

:: check command line args for configuration
:CheckConfiguration
@if "%~1"=="-c" (@set PL_CONFIG=%2) & @shift & @shift & @goto CheckConfiguration
@if "%PL_CONFIG%" equ "debug" ( goto debug )
@if "%PL_CONFIG%" equ "release" ( goto release )
@if "%PL_CONFIG%" equ "moltenvk" ( goto moltenvk )
@if "%PL_CONFIG%" equ "debug_editor" ( goto debug_editor )
@if "%PL_CONFIG%" equ "release_editor" ( goto release_editor )
@if "%PL_CONFIG%" equ "moltenvk_editor" ( goto moltenvk_editor )

:: ################################################################################
:: #                            configuration | debug                             #
:: ################################################################################

:debug

:: create output directories
@if not exist "../out" @mkdir "../out"

:: create lock file(s)
@echo LOCKING > "../out/lock.tmp"

:: check if this is a hot reload
@set PL_HOT_RELOAD_STATUS=0

:: hack to see if hot reload target exes are running
@echo off
2>nul (>>"../out/pilot_light.exe" echo off) && (@set PL_HOT_RELOAD_STATUS=%PL_HOT_RELOAD_STATUS%) || (@set PL_HOT_RELOAD_STATUS=1)
2>nul (>>"../out/pl_editor.exe" echo off) && (@set PL_HOT_RELOAD_STATUS=%PL_HOT_RELOAD_STATUS%) || (@set PL_HOT_RELOAD_STATUS=1)

:: let user know if hot reloading
@if %PL_HOT_RELOAD_STATUS% equ 1 (
    @echo [1m[97m[41m--------[42m HOT RELOADING [41m--------[0m
)

:: cleanup binaries if not hot reloading
@if %PL_HOT_RELOAD_STATUS% equ 0 (

    @if exist "../out/pl_unity_ext.dll" del "..\out\pl_unity_ext.dll"
    @if exist "../out/pl_unity_ext_*.dll" del "..\out\pl_unity_ext_*.dll"
    @if exist "../out/pl_unity_ext_*.pdb" del "..\out\pl_unity_ext_*.pdb"
    @if exist "../out/pl_script_camera.dll" del "..\out\pl_script_camera.dll"
    @if exist "../out/pl_script_camera_*.dll" del "..\out\pl_script_camera_*.dll"
    @if exist "../out/pl_script_camera_*.pdb" del "..\out\pl_script_camera_*.pdb"
    @if exist "../out/pl_platform_ext.dll" del "..\out\pl_platform_ext.dll"
    @if exist "../out/pl_platform_ext_*.dll" del "..\out\pl_platform_ext_*.dll"
    @if exist "../out/pl_platform_ext_*.pdb" del "..\out\pl_platform_ext_*.pdb"
    @if exist "../out/app.dll" del "..\out\app.dll"
    @if exist "../out/app_*.dll" del "..\out\app_*.dll"
    @if exist "../out/app_*.pdb" del "..\out\app_*.pdb"
    @if exist "../out/pilot_light.exe" del "..\out\pilot_light.exe"
    @if exist "../out/pilot_light_*.pdb" del "..\out\pilot_light_*.pdb"

)

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ pl_unity_ext | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

@set PL_DEFINES=-DPL_UNITY_BUILD -DPL_INCLUDE_SPIRV_CROSS -DPL_VULKAN_BACKEND -DPL_UNITY_BUILD -D_DEBUG -DPL_CONFIG_DEBUG 
@set PL_INCLUDE_DIRECTORIES=-I"../editor" -I"../src" -I"../libs" -I"../extensions" -I"../out" -I"../dependencies/stb" -I"../dependencies/cgltf" -I"../dependencies/imgui" -I"../dependencies/glfw/include" -I"%WindowsSdkDir%Include\um" -I"%WindowsSdkDir%Include\shared" -I"%VULKAN_SDK%\Include" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../out" -LIBPATH:"%VULKAN_SDK%\Lib" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -permissive- -Od -MDd -Zi -std:c11 
@set PL_LINKER_FLAGS=-noimplib -noexp -incremental:no -nodefaultlib:MSVCRT 
@set PL_STATIC_LINK_LIBRARIES=shaderc_combined.lib spirv-cross-c-shared.lib vulkan-1.lib 
@set PL_SOURCES="../extensions/pl_unity_ext.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: pl_unity_ext[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_INCLUDE_DIRECTORIES% %PL_DEFINES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../out/pl_unity_ext.dll" -Fo"../out/" -LD -link %PL_LINKER_FLAGS% -PDB:"../out/pl_unity_ext_%random%.pdb" %PL_LINK_DIRECTORIES% %PL_STATIC_LINK_LIBRARIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

@del "..\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~ pl_script_camera | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~

@set PL_DEFINES=-DPL_UNITY_BUILD -DPL_VULKAN_BACKEND -DPL_UNITY_BUILD -D_DEBUG -DPL_CONFIG_DEBUG 
@set PL_INCLUDE_DIRECTORIES=-I"../editor" -I"../src" -I"../libs" -I"../extensions" -I"../out" -I"../dependencies/stb" -I"../dependencies/cgltf" -I"../dependencies/imgui" -I"../dependencies/glfw/include" -I"%WindowsSdkDir%Include\um" -I"%WindowsSdkDir%Include\shared" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../out" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -permissive- -Od -MDd -Zi -std:c11 
@set PL_LINKER_FLAGS=-noimplib -noexp -incremental:no 
@set PL_SOURCES="../extensions/pl_script_camera.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: pl_script_camera[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_INCLUDE_DIRECTORIES% %PL_DEFINES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../out/pl_script_camera.dll" -Fo"../out/" -LD -link %PL_LINKER_FLAGS% -PDB:"../out/pl_script_camera_%random%.pdb" %PL_LINK_DIRECTORIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

@del "..\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~ pl_platform_ext | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

:: skip during hot reload
@if %PL_HOT_RELOAD_STATUS% equ 1 goto Exit_pl_platform_ext

@set PL_DEFINES=-DPL_UNITY_BUILD -DPL_VULKAN_BACKEND -DPL_UNITY_BUILD -D_DEBUG -DPL_CONFIG_DEBUG 
@set PL_INCLUDE_DIRECTORIES=-I"../editor" -I"../src" -I"../libs" -I"../extensions" -I"../out" -I"../dependencies/stb" -I"../dependencies/cgltf" -I"../dependencies/imgui" -I"../dependencies/glfw/include" -I"%WindowsSdkDir%Include\um" -I"%WindowsSdkDir%Include\shared" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../out" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -permissive- -Od -MDd -Zi -std:c11 
@set PL_LINKER_FLAGS=-noimplib -noexp -incremental:no 
@set PL_STATIC_LINK_LIBRARIES=ucrtd.lib user32.lib Ole32.lib 
@set PL_SOURCES="../extensions/pl_platform_win32_ext.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: pl_platform_ext[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_INCLUDE_DIRECTORIES% %PL_DEFINES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../out/pl_platform_ext.dll" -Fo"../out/" -LD -link %PL_LINKER_FLAGS% -PDB:"../out/pl_platform_ext_%random%.pdb" %PL_LINK_DIRECTORIES% %PL_STATIC_LINK_LIBRARIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_pl_platform_ext

@del "..\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ app | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

@set PL_DEFINES=-DPL_UNITY_BUILD -DPL_VULKAN_BACKEND -DPL_UNITY_BUILD -D_DEBUG -DPL_CONFIG_DEBUG 
@set PL_INCLUDE_DIRECTORIES=-I"../editor" -I"../src" -I"../libs" -I"../extensions" -I"../out" -I"../dependencies/stb" -I"../dependencies/cgltf" -I"../dependencies/imgui" -I"../dependencies/glfw/include" -I"%WindowsSdkDir%Include\um" -I"%WindowsSdkDir%Include\shared" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../out" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -permissive- -Od -MDd -Zi 
@set PL_LINKER_FLAGS=-noimplib -noexp -incremental:no 
@set PL_SOURCES="../editor/app.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: app[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_INCLUDE_DIRECTORIES% %PL_DEFINES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../out/app.dll" -Fo"../out/" -LD -link %PL_LINKER_FLAGS% -PDB:"../out/app_%random%.pdb" %PL_LINK_DIRECTORIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

@del "..\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ pilot_light | debug ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

:: skip during hot reload
@if %PL_HOT_RELOAD_STATUS% equ 1 goto Exit_pilot_light

@set PL_DEFINES=-DPL_UNITY_BUILD -DPL_VULKAN_BACKEND -DPL_UNITY_BUILD -D_DEBUG -DPL_CONFIG_DEBUG 
@set PL_INCLUDE_DIRECTORIES=-I"../editor" -I"../src" -I"../libs" -I"../extensions" -I"../out" -I"../dependencies/stb" -I"../dependencies/cgltf" -I"../dependencies/imgui" -I"../dependencies/glfw/include" -I"%WindowsSdkDir%Include\um" -I"%WindowsSdkDir%Include\shared" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../out" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -permissive- -Od -MDd -Zi -std:c11 
@set PL_LINKER_FLAGS=-incremental:no 
@set PL_STATIC_LINK_LIBRARIES=ucrtd.lib user32.lib Ole32.lib 
@set PL_SOURCES="pl_main_win32.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: pilot_light[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m

:: skip actual compilation if hot reloading
@if %PL_HOT_RELOAD_STATUS% equ 1 ( goto Cleanuppilot_light )

:: call compiler
cl %PL_INCLUDE_DIRECTORIES% %PL_DEFINES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../out/pilot_light.exe" -Fo"../out/" -link %PL_LINKER_FLAGS% -PDB:"../out/pilot_light_%random%.pdb" %PL_LINK_DIRECTORIES% %PL_STATIC_LINK_LIBRARIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_pilot_light

@del "..\out\*.obj"  > nul 2> nul

:Cleanupdebug

@echo [1m[36mCleaning...[0m

:: delete obj files(s)
@del "..\out\*.obj"  > nul 2> nul

:: delete lock file(s)
@if exist "../out/lock.tmp" del "..\out\lock.tmp"

:: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
:: end of debug configuration
goto ExitLabel

:: ################################################################################
:: #                           configuration | release                            #
:: ################################################################################

:release

:: create output directories
@if not exist "../out" @mkdir "../out"

:: create lock file(s)
@echo LOCKING > "../out/lock.tmp"

:: check if this is a hot reload
@set PL_HOT_RELOAD_STATUS=0

:: hack to see if hot reload target exes are running
@echo off
2>nul (>>"../out/pilot_light.exe" echo off) && (@set PL_HOT_RELOAD_STATUS=%PL_HOT_RELOAD_STATUS%) || (@set PL_HOT_RELOAD_STATUS=1)
2>nul (>>"../out/pl_editor.exe" echo off) && (@set PL_HOT_RELOAD_STATUS=%PL_HOT_RELOAD_STATUS%) || (@set PL_HOT_RELOAD_STATUS=1)

:: let user know if hot reloading
@if %PL_HOT_RELOAD_STATUS% equ 1 (
    @echo [1m[97m[41m--------[42m HOT RELOADING [41m--------[0m
)

:: cleanup binaries if not hot reloading
@if %PL_HOT_RELOAD_STATUS% equ 0 (

    @if exist "../out/pl_unity_ext.dll" del "..\out\pl_unity_ext.dll"
    @if exist "../out/pl_unity_ext_*.dll" del "..\out\pl_unity_ext_*.dll"
    @if exist "../out/pl_unity_ext_*.pdb" del "..\out\pl_unity_ext_*.pdb"
    @if exist "../out/pl_script_camera.dll" del "..\out\pl_script_camera.dll"
    @if exist "../out/pl_script_camera_*.dll" del "..\out\pl_script_camera_*.dll"
    @if exist "../out/pl_script_camera_*.pdb" del "..\out\pl_script_camera_*.pdb"
    @if exist "../out/pl_platform_ext.dll" del "..\out\pl_platform_ext.dll"
    @if exist "../out/pl_platform_ext_*.dll" del "..\out\pl_platform_ext_*.dll"
    @if exist "../out/pl_platform_ext_*.pdb" del "..\out\pl_platform_ext_*.pdb"
    @if exist "../out/app.dll" del "..\out\app.dll"
    @if exist "../out/app_*.dll" del "..\out\app_*.dll"
    @if exist "../out/app_*.pdb" del "..\out\app_*.pdb"
    @if exist "../out/pilot_light.exe" del "..\out\pilot_light.exe"
    @if exist "../out/pilot_light_*.pdb" del "..\out\pilot_light_*.pdb"

)

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~ pl_unity_ext | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

@set PL_DEFINES=-DPL_UNITY_BUILD -DPL_INCLUDE_SPIRV_CROSS -DPL_VULKAN_BACKEND -DPL_UNITY_BUILD -DNDEBUG -DPL_CONFIG_RELEASE 
@set PL_INCLUDE_DIRECTORIES=-I"../editor" -I"../src" -I"../libs" -I"../extensions" -I"../out" -I"../dependencies/stb" -I"../dependencies/cgltf" -I"../dependencies/imgui" -I"../dependencies/glfw/include" -I"%WindowsSdkDir%Include\um" -I"%WindowsSdkDir%Include\shared" -I"%VULKAN_SDK%\Include" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../out" -LIBPATH:"%VULKAN_SDK%\Lib" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -permissive- -O2 -MD -std:c11 
@set PL_LINKER_FLAGS=-noimplib -noexp -incremental:no 
@set PL_STATIC_LINK_LIBRARIES=shaderc_combined.lib spirv-cross-c-shared.lib vulkan-1.lib 
@set PL_SOURCES="../extensions/pl_unity_ext.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: pl_unity_ext[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_INCLUDE_DIRECTORIES% %PL_DEFINES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../out/pl_unity_ext.dll" -Fo"../out/" -LD -link %PL_LINKER_FLAGS% -PDB:"../out/pl_unity_ext_%random%.pdb" %PL_LINK_DIRECTORIES% %PL_STATIC_LINK_LIBRARIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

@del "..\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~ pl_script_camera | release ~~~~~~~~~~~~~~~~~~~~~~~~~~

@set PL_DEFINES=-DPL_UNITY_BUILD -DPL_VULKAN_BACKEND -DPL_UNITY_BUILD -DNDEBUG -DPL_CONFIG_RELEASE 
@set PL_INCLUDE_DIRECTORIES=-I"../editor" -I"../src" -I"../libs" -I"../extensions" -I"../out" -I"../dependencies/stb" -I"../dependencies/cgltf" -I"../dependencies/imgui" -I"../dependencies/glfw/include" -I"%WindowsSdkDir%Include\um" -I"%WindowsSdkDir%Include\shared" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../out" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -permissive- -O2 -MD -std:c11 
@set PL_LINKER_FLAGS=-noimplib -noexp -incremental:no 
@set PL_SOURCES="../extensions/pl_script_camera.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: pl_script_camera[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_INCLUDE_DIRECTORIES% %PL_DEFINES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../out/pl_script_camera.dll" -Fo"../out/" -LD -link %PL_LINKER_FLAGS% -PDB:"../out/pl_script_camera_%random%.pdb" %PL_LINK_DIRECTORIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

@del "..\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~ pl_platform_ext | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~

:: skip during hot reload
@if %PL_HOT_RELOAD_STATUS% equ 1 goto Exit_pl_platform_ext

@set PL_DEFINES=-DPL_UNITY_BUILD -DPL_VULKAN_BACKEND -DPL_UNITY_BUILD -DNDEBUG -DPL_CONFIG_RELEASE 
@set PL_INCLUDE_DIRECTORIES=-I"../editor" -I"../src" -I"../libs" -I"../extensions" -I"../out" -I"../dependencies/stb" -I"../dependencies/cgltf" -I"../dependencies/imgui" -I"../dependencies/glfw/include" -I"%WindowsSdkDir%Include\um" -I"%WindowsSdkDir%Include\shared" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../out" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -permissive- -O2 -MD -std:c11 
@set PL_LINKER_FLAGS=-noimplib -noexp -incremental:no 
@set PL_STATIC_LINK_LIBRARIES=ucrt.lib user32.lib Ole32.lib 
@set PL_SOURCES="../extensions/pl_platform_win32_ext.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: pl_platform_ext[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_INCLUDE_DIRECTORIES% %PL_DEFINES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../out/pl_platform_ext.dll" -Fo"../out/" -LD -link %PL_LINKER_FLAGS% -PDB:"../out/pl_platform_ext_%random%.pdb" %PL_LINK_DIRECTORIES% %PL_STATIC_LINK_LIBRARIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_pl_platform_ext

@del "..\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ app | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

@set PL_DEFINES=-DPL_UNITY_BUILD -DPL_VULKAN_BACKEND -DPL_UNITY_BUILD -DNDEBUG -DPL_CONFIG_RELEASE 
@set PL_INCLUDE_DIRECTORIES=-I"../editor" -I"../src" -I"../libs" -I"../extensions" -I"../out" -I"../dependencies/stb" -I"../dependencies/cgltf" -I"../dependencies/imgui" -I"../dependencies/glfw/include" -I"%WindowsSdkDir%Include\um" -I"%WindowsSdkDir%Include\shared" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../out" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -permissive- -O2 -MD 
@set PL_LINKER_FLAGS=-noimplib -noexp -incremental:no 
@set PL_SOURCES="../editor/app.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: app[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_INCLUDE_DIRECTORIES% %PL_DEFINES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../out/app.dll" -Fo"../out/" -LD -link %PL_LINKER_FLAGS% -PDB:"../out/app_%random%.pdb" %PL_LINK_DIRECTORIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

@del "..\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~ pilot_light | release ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

:: skip during hot reload
@if %PL_HOT_RELOAD_STATUS% equ 1 goto Exit_pilot_light

@set PL_DEFINES=-DPL_UNITY_BUILD -DPL_VULKAN_BACKEND -DPL_UNITY_BUILD -DNDEBUG -DPL_CONFIG_RELEASE 
@set PL_INCLUDE_DIRECTORIES=-I"../editor" -I"../src" -I"../libs" -I"../extensions" -I"../out" -I"../dependencies/stb" -I"../dependencies/cgltf" -I"../dependencies/imgui" -I"../dependencies/glfw/include" -I"%WindowsSdkDir%Include\um" -I"%WindowsSdkDir%Include\shared" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../out" 
@set PL_COMPILER_FLAGS=-Zc:preprocessor -nologo -W4 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -permissive- -O2 -MD -std:c11 
@set PL_LINKER_FLAGS=-incremental:no 
@set PL_STATIC_LINK_LIBRARIES=ucrt.lib user32.lib Ole32.lib 
@set PL_SOURCES="pl_main_win32.c" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: pilot_light[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m

:: skip actual compilation if hot reloading
@if %PL_HOT_RELOAD_STATUS% equ 1 ( goto Cleanuppilot_light )

:: call compiler
cl %PL_INCLUDE_DIRECTORIES% %PL_DEFINES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../out/pilot_light.exe" -Fo"../out/" -link %PL_LINKER_FLAGS% -PDB:"../out/pilot_light_%random%.pdb" %PL_LINK_DIRECTORIES% %PL_STATIC_LINK_LIBRARIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_pilot_light

@del "..\out\*.obj"  > nul 2> nul

:Cleanuprelease

@echo [1m[36mCleaning...[0m

:: delete obj files(s)
@del "..\out\*.obj"  > nul 2> nul

:: delete lock file(s)
@if exist "../out/lock.tmp" del "..\out\lock.tmp"

:: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
:: end of release configuration
goto ExitLabel

:: ################################################################################
:: #                         configuration | debug_editor                         #
:: ################################################################################

:debug_editor

:: create output directories
@if not exist "../out" @mkdir "../out"

:: create lock file(s)
@echo LOCKING > "../out/lock.tmp"

:: check if this is a hot reload
@set PL_HOT_RELOAD_STATUS=0

:: hack to see if hot reload target exes are running
@echo off
2>nul (>>"../out/pilot_light.exe" echo off) && (@set PL_HOT_RELOAD_STATUS=%PL_HOT_RELOAD_STATUS%) || (@set PL_HOT_RELOAD_STATUS=1)
2>nul (>>"../out/pl_editor.exe" echo off) && (@set PL_HOT_RELOAD_STATUS=%PL_HOT_RELOAD_STATUS%) || (@set PL_HOT_RELOAD_STATUS=1)

:: let user know if hot reloading
@if %PL_HOT_RELOAD_STATUS% equ 1 (
    @echo [1m[97m[41m--------[42m HOT RELOADING [41m--------[0m
)

:: cleanup binaries if not hot reloading
@if %PL_HOT_RELOAD_STATUS% equ 0 (

    @if exist "../out/editor.dll" del "..\out\editor.dll"
    @if exist "../out/editor_*.dll" del "..\out\editor_*.dll"
    @if exist "../out/editor_*.pdb" del "..\out\editor_*.pdb"
    @if exist "../out/pl_dear_imgui_ext.dll" del "..\out\pl_dear_imgui_ext.dll"
    @if exist "../out/pl_dear_imgui_ext_*.dll" del "..\out\pl_dear_imgui_ext_*.dll"
    @if exist "../out/pl_dear_imgui_ext_*.pdb" del "..\out\pl_dear_imgui_ext_*.pdb"
    @if exist "../out/pl_editor.exe" del "..\out\pl_editor.exe"
    @if exist "../out/pl_editor_*.pdb" del "..\out\pl_editor_*.pdb"

)

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ glfw | debug_editor ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

:: skip during hot reload
@if %PL_HOT_RELOAD_STATUS% equ 1 goto Exit_glfw

:: only build once
@if exist "..\out\glfwd.lib" goto Exit_glfw

@set PL_DEFINES=-DPL_UNITY_BUILD -DUNICODE -D_UNICODE -D_CRT_SECURE_NO_WARNINGS -D_GLFW_VULKAN_STATIC -D_GLFW_WIN32 -D_DEBUG 
@set PL_INCLUDE_DIRECTORIES=-I"../editor" -I"../src" -I"../libs" -I"../extensions" -I"../out" -I"../dependencies/stb" -I"../dependencies/cgltf" -I"../dependencies/imgui" -I"../dependencies/glfw/include" -I"%VULKAN_SDK%\Include" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../out" 
@set PL_COMPILER_FLAGS=-nologo -std:c11 -W3 -wd5105 -Od -MDd -Zi -permissive 
@set PL_LINKER_FLAGS=-incremental:no -nologo 

:: run compiler only
@echo.
@echo [1m[93mStep: glfw[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling...[0m

:: each file must be compiled separately
cl -c %PL_INCLUDE_DIRECTORIES% %PL_DEFINES% %PL_COMPILER_FLAGS% ../dependencies/glfw/src/glfw_unity.c -Fo"../out/"

cl -c %PL_INCLUDE_DIRECTORIES% %PL_DEFINES% %PL_COMPILER_FLAGS% ../dependencies/glfw/src/null_window.c -Fo"../out/"


:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: if failed, skip linking
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug_editor
)

:: link object files into a shared lib
@echo [1m[36mLinking...[0m
lib -nologo -OUT:"../out/glfwd.lib" "../out/*.obj"

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_glfw

@del "..\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ imgui | debug_editor ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

:: skip during hot reload
@if %PL_HOT_RELOAD_STATUS% equ 1 goto Exit_imgui

:: only build once
@if exist "..\out\dearimguid.lib" goto Exit_imgui

@set PL_DEFINES=-DPL_UNITY_BUILD 
@set PL_INCLUDE_DIRECTORIES=-I"../editor" -I"../src" -I"../libs" -I"../extensions" -I"../out" -I"../dependencies/stb" -I"../dependencies/cgltf" -I"../dependencies/imgui" -I"../dependencies/glfw/include" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../out" 
@set PL_COMPILER_FLAGS=-nologo -std:c++14 -WX -Od -MDd -Zi -permissive 
@set PL_LINKER_FLAGS=-incremental:no -nologo 

:: run compiler only
@echo.
@echo [1m[93mStep: imgui[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling...[0m

:: each file must be compiled separately
cl -c %PL_INCLUDE_DIRECTORIES% %PL_DEFINES% %PL_COMPILER_FLAGS% ../dependencies/imgui/imgui_unity.cpp -Fo"../out/"


:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: if failed, skip linking
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug_editor
)

:: link object files into a shared lib
@echo [1m[36mLinking...[0m
lib -nologo -OUT:"../out/dearimguid.lib" "../out/*.obj"

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_imgui

@del "..\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~ editor app | debug_editor ~~~~~~~~~~~~~~~~~~~~~~~~~~~

@set PL_DEFINES=-DPL_UNITY_BUILD 
@set PL_INCLUDE_DIRECTORIES=-I"../editor" -I"../src" -I"../libs" -I"../extensions" -I"../out" -I"../dependencies/stb" -I"../dependencies/cgltf" -I"../dependencies/imgui" -I"../dependencies/glfw/include" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../out" 
@set PL_COMPILER_FLAGS=-nologo -std:c++14 -W3 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -Od -MDd -Zi -permissive 
@set PL_LINKER_FLAGS=-incremental:no -nologo -noimplib -noexp 
@set PL_STATIC_LINK_LIBRARIES=dearimguid.lib 
@set PL_SOURCES="../editor/editor.cpp" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: editor app[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_INCLUDE_DIRECTORIES% %PL_DEFINES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../out/editor.dll" -Fo"../out/" -LD -link %PL_LINKER_FLAGS% -PDB:"../out/editor_%random%.pdb" %PL_LINK_DIRECTORIES% %PL_STATIC_LINK_LIBRARIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug_editor
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

@del "..\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~ pl_dear_imgui_ext | debug_editor ~~~~~~~~~~~~~~~~~~~~~~~

:: skip during hot reload
@if %PL_HOT_RELOAD_STATUS% equ 1 goto Exit_pl_dear_imgui_ext

@set PL_DEFINES=-DPL_UNITY_BUILD -DPL_VULKAN_BACKEND 
@set PL_INCLUDE_DIRECTORIES=-I"../editor" -I"../src" -I"../libs" -I"../extensions" -I"../out" -I"../dependencies/stb" -I"../dependencies/cgltf" -I"../dependencies/imgui" -I"../dependencies/glfw/include" -I"%VULKAN_SDK%\Include" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../out" -LIBPATH:"%VULKAN_SDK%\Lib" 
@set PL_COMPILER_FLAGS=-nologo -std:c++14 -W3 -WX -Od -MDd -Zi -permissive 
@set PL_LINKER_FLAGS=-incremental:no -nologo -noimplib -noexp 
@set PL_STATIC_LINK_LIBRARIES=glfwd.lib dearimguid.lib ucrtd.lib vulkan-1.lib 
@set PL_SOURCES="../editor/pl_dear_imgui_ext.cpp" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: pl_dear_imgui_ext[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_INCLUDE_DIRECTORIES% %PL_DEFINES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../out/pl_dear_imgui_ext.dll" -Fo"../out/" -LD -link %PL_LINKER_FLAGS% -PDB:"../out/pl_dear_imgui_ext_%random%.pdb" %PL_LINK_DIRECTORIES% %PL_STATIC_LINK_LIBRARIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug_editor
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_pl_dear_imgui_ext

@del "..\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~ pilot_light_editor | debug_editor ~~~~~~~~~~~~~~~~~~~~~~~

:: skip during hot reload
@if %PL_HOT_RELOAD_STATUS% equ 1 goto Exit_pilot_light_editor

@set PL_DEFINES=-DPL_UNITY_BUILD -DPL_VULKAN_BACKEND 
@set PL_INCLUDE_DIRECTORIES=-I"../editor" -I"../src" -I"../libs" -I"../extensions" -I"../out" -I"../dependencies/stb" -I"../dependencies/cgltf" -I"../dependencies/imgui" -I"../dependencies/glfw/include" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../out" 
@set PL_COMPILER_FLAGS=-nologo -std:c++14 -W3 -WX -wd4996 -Od -MDd -Zi -permissive 
@set PL_LINKER_FLAGS=-incremental:no -nologo 
@set PL_STATIC_LINK_LIBRARIES=glfwd.lib dearimguid.lib user32.lib Shell32.lib Ole32.lib gdi32.lib ucrtd.lib 
@set PL_SOURCES="../editor/pl_main_glfw.cpp" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: pilot_light_editor[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m

:: skip actual compilation if hot reloading
@if %PL_HOT_RELOAD_STATUS% equ 1 ( goto Cleanuppilot_light_editor )

:: call compiler
cl %PL_INCLUDE_DIRECTORIES% %PL_DEFINES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../out/pl_editor.exe" -Fo"../out/" -link %PL_LINKER_FLAGS% -PDB:"../out/pl_editor_%random%.pdb" %PL_LINK_DIRECTORIES% %PL_STATIC_LINK_LIBRARIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanupdebug_editor
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_pilot_light_editor

@del "..\out\*.obj"  > nul 2> nul

:Cleanupdebug_editor

@echo [1m[36mCleaning...[0m

:: delete obj files(s)
@del "..\out\*.obj"  > nul 2> nul

:: delete lock file(s)
@if exist "../out/lock.tmp" del "..\out\lock.tmp"

:: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
:: end of debug_editor configuration
goto ExitLabel

:: ################################################################################
:: #                        configuration | release_editor                        #
:: ################################################################################

:release_editor

:: create output directories
@if not exist "../out" @mkdir "../out"

:: create lock file(s)
@echo LOCKING > "../out/lock.tmp"

:: check if this is a hot reload
@set PL_HOT_RELOAD_STATUS=0

:: hack to see if hot reload target exes are running
@echo off
2>nul (>>"../out/pilot_light.exe" echo off) && (@set PL_HOT_RELOAD_STATUS=%PL_HOT_RELOAD_STATUS%) || (@set PL_HOT_RELOAD_STATUS=1)
2>nul (>>"../out/pl_editor.exe" echo off) && (@set PL_HOT_RELOAD_STATUS=%PL_HOT_RELOAD_STATUS%) || (@set PL_HOT_RELOAD_STATUS=1)

:: let user know if hot reloading
@if %PL_HOT_RELOAD_STATUS% equ 1 (
    @echo [1m[97m[41m--------[42m HOT RELOADING [41m--------[0m
)

:: cleanup binaries if not hot reloading
@if %PL_HOT_RELOAD_STATUS% equ 0 (

    @if exist "../out/editor.dll" del "..\out\editor.dll"
    @if exist "../out/editor_*.dll" del "..\out\editor_*.dll"
    @if exist "../out/editor_*.pdb" del "..\out\editor_*.pdb"
    @if exist "../out/pl_dear_imgui_ext.dll" del "..\out\pl_dear_imgui_ext.dll"
    @if exist "../out/pl_dear_imgui_ext_*.dll" del "..\out\pl_dear_imgui_ext_*.dll"
    @if exist "../out/pl_dear_imgui_ext_*.pdb" del "..\out\pl_dear_imgui_ext_*.pdb"
    @if exist "../out/pl_editor.exe" del "..\out\pl_editor.exe"
    @if exist "../out/pl_editor_*.pdb" del "..\out\pl_editor_*.pdb"

)

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~ glfw | release_editor ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

:: skip during hot reload
@if %PL_HOT_RELOAD_STATUS% equ 1 goto Exit_glfw

:: only build once
@if exist "..\out\glfw.lib" goto Exit_glfw

@set PL_DEFINES=-DPL_UNITY_BUILD -DUNICODE -D_UNICODE -D_CRT_SECURE_NO_WARNINGS -D_GLFW_VULKAN_STATIC -D_GLFW_WIN32 
@set PL_INCLUDE_DIRECTORIES=-I"../editor" -I"../src" -I"../libs" -I"../extensions" -I"../out" -I"../dependencies/stb" -I"../dependencies/cgltf" -I"../dependencies/imgui" -I"../dependencies/glfw/include" -I"%VULKAN_SDK%\Include" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../out" 
@set PL_COMPILER_FLAGS=-nologo -std:c11 -W3 -wd5105 -O2 -MD -Zi -permissive 
@set PL_LINKER_FLAGS=-incremental:no -nologo 

:: run compiler only
@echo.
@echo [1m[93mStep: glfw[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling...[0m

:: each file must be compiled separately
cl -c %PL_INCLUDE_DIRECTORIES% %PL_DEFINES% %PL_COMPILER_FLAGS% ../dependencies/glfw/src/glfw_unity.c -Fo"../out/"

cl -c %PL_INCLUDE_DIRECTORIES% %PL_DEFINES% %PL_COMPILER_FLAGS% ../dependencies/glfw/src/null_window.c -Fo"../out/"


:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: if failed, skip linking
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease_editor
)

:: link object files into a shared lib
@echo [1m[36mLinking...[0m
lib -nologo -OUT:"../out/glfw.lib" "../out/*.obj"

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_glfw

@del "..\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~~~~ imgui | release_editor ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

:: skip during hot reload
@if %PL_HOT_RELOAD_STATUS% equ 1 goto Exit_imgui

:: only build once
@if exist "..\out\dearimgui.lib" goto Exit_imgui

@set PL_DEFINES=-DPL_UNITY_BUILD 
@set PL_INCLUDE_DIRECTORIES=-I"../editor" -I"../src" -I"../libs" -I"../extensions" -I"../out" -I"../dependencies/stb" -I"../dependencies/cgltf" -I"../dependencies/imgui" -I"../dependencies/glfw/include" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../out" 
@set PL_COMPILER_FLAGS=-nologo -std:c++14 -WX -O2 -MD -permissive 
@set PL_LINKER_FLAGS=-incremental:no -nologo 

:: run compiler only
@echo.
@echo [1m[93mStep: imgui[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling...[0m

:: each file must be compiled separately
cl -c %PL_INCLUDE_DIRECTORIES% %PL_DEFINES% %PL_COMPILER_FLAGS% ../dependencies/imgui/imgui_unity.cpp -Fo"../out/"


:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: if failed, skip linking
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease_editor
)

:: link object files into a shared lib
@echo [1m[36mLinking...[0m
lib -nologo -OUT:"../out/dearimgui.lib" "../out/*.obj"

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_imgui

@del "..\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~~~~ editor app | release_editor ~~~~~~~~~~~~~~~~~~~~~~~~~~

@set PL_DEFINES=-DPL_UNITY_BUILD 
@set PL_INCLUDE_DIRECTORIES=-I"../editor" -I"../src" -I"../libs" -I"../extensions" -I"../out" -I"../dependencies/stb" -I"../dependencies/cgltf" -I"../dependencies/imgui" -I"../dependencies/glfw/include" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../out" 
@set PL_COMPILER_FLAGS=-nologo -std:c++14 -W3 -WX -wd4201 -wd4100 -wd4996 -wd4505 -wd4189 -wd5105 -wd4115 -O2 -MD -permissive 
@set PL_LINKER_FLAGS=-incremental:no -nologo -noimplib -noexp 
@set PL_STATIC_LINK_LIBRARIES=dearimgui.lib 
@set PL_SOURCES="../editor/editor.cpp" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: editor app[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_INCLUDE_DIRECTORIES% %PL_DEFINES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../out/editor.dll" -Fo"../out/" -LD -link %PL_LINKER_FLAGS% -PDB:"../out/editor_%random%.pdb" %PL_LINK_DIRECTORIES% %PL_STATIC_LINK_LIBRARIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease_editor
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

@del "..\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~~ pl_dear_imgui_ext | release_editor ~~~~~~~~~~~~~~~~~~~~~~

:: skip during hot reload
@if %PL_HOT_RELOAD_STATUS% equ 1 goto Exit_pl_dear_imgui_ext

@set PL_DEFINES=-DPL_UNITY_BUILD -DPL_VULKAN_BACKEND 
@set PL_INCLUDE_DIRECTORIES=-I"../editor" -I"../src" -I"../libs" -I"../extensions" -I"../out" -I"../dependencies/stb" -I"../dependencies/cgltf" -I"../dependencies/imgui" -I"../dependencies/glfw/include" -I"%VULKAN_SDK%\Include" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../out" -LIBPATH:"%VULKAN_SDK%\Lib" 
@set PL_COMPILER_FLAGS=-nologo -std:c++14 -W3 -WX -O2 -MD -permissive 
@set PL_LINKER_FLAGS=-incremental:no -nologo -noimplib -noexp 
@set PL_STATIC_LINK_LIBRARIES=glfw.lib dearimgui.lib ucrtd.lib vulkan-1.lib 
@set PL_SOURCES="../editor/pl_dear_imgui_ext.cpp" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: pl_dear_imgui_ext[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m
cl %PL_INCLUDE_DIRECTORIES% %PL_DEFINES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../out/pl_dear_imgui_ext.dll" -Fo"../out/" -LD -link %PL_LINKER_FLAGS% -PDB:"../out/pl_dear_imgui_ext_%random%.pdb" %PL_LINK_DIRECTORIES% %PL_STATIC_LINK_LIBRARIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease_editor
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_pl_dear_imgui_ext

@del "..\out\*.obj"  > nul 2> nul

::~~~~~~~~~~~~~~~~~~~~~ pilot_light_editor | release_editor ~~~~~~~~~~~~~~~~~~~~~~

:: skip during hot reload
@if %PL_HOT_RELOAD_STATUS% equ 1 goto Exit_pilot_light_editor

@set PL_DEFINES=-DPL_UNITY_BUILD -DPL_VULKAN_BACKEND 
@set PL_INCLUDE_DIRECTORIES=-I"../editor" -I"../src" -I"../libs" -I"../extensions" -I"../out" -I"../dependencies/stb" -I"../dependencies/cgltf" -I"../dependencies/imgui" -I"../dependencies/glfw/include" 
@set PL_LINK_DIRECTORIES=-LIBPATH:"../out" 
@set PL_COMPILER_FLAGS=-nologo -std:c++14 -W3 -WX -wd4996 -O2 -MD -permissive 
@set PL_LINKER_FLAGS=-incremental:no -nologo 
@set PL_STATIC_LINK_LIBRARIES=glfw.lib dearimgui.lib user32.lib Shell32.lib Ole32.lib gdi32.lib ucrtd.lib 
@set PL_SOURCES="../editor/pl_main_glfw.cpp" 

:: run compiler (and linker)
@echo.
@echo [1m[93mStep: pilot_light_editor[0m
@echo [1m[93m~~~~~~~~~~~~~~~~~~~~~~[0m
@echo [1m[36mCompiling and Linking...[0m

:: skip actual compilation if hot reloading
@if %PL_HOT_RELOAD_STATUS% equ 1 ( goto Cleanuppilot_light_editor )

:: call compiler
cl %PL_INCLUDE_DIRECTORIES% %PL_DEFINES% %PL_COMPILER_FLAGS% %PL_SOURCES% -Fe"../out/pl_editor.exe" -Fo"../out/" -link %PL_LINKER_FLAGS% -PDB:"../out/pl_editor_%random%.pdb" %PL_LINK_DIRECTORIES% %PL_STATIC_LINK_LIBRARIES%

:: check build status
@set PL_BUILD_STATUS=%ERRORLEVEL%

:: failed
@if %PL_BUILD_STATUS% NEQ 0 (
    @echo [1m[91mCompilation Failed with error code[0m: %PL_BUILD_STATUS%
    @set PL_RESULT=[1m[91mFailed.[0m
    goto Cleanuprelease_editor
)

:: print results
@echo [36mResult: [0m %PL_RESULT%
@echo [36m~~~~~~~~~~~~~~~~~~~~~~[0m

:Exit_pilot_light_editor

@del "..\out\*.obj"  > nul 2> nul

:Cleanuprelease_editor

@echo [1m[36mCleaning...[0m

:: delete obj files(s)
@del "..\out\*.obj"  > nul 2> nul

:: delete lock file(s)
@if exist "../out/lock.tmp" del "..\out\lock.tmp"

:: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
:: end of release_editor configuration
goto ExitLabel

:ExitLabel

:: return CWD to previous CWD
@popd
