name: Build

on:

  schedule:
    - cron: '0 1 * * 1'

  push:

    branches:
      - master
      - dev
      - feature/*
      - dev/*
      - fix/*

  pull_request:

  workflow_dispatch:
    
jobs:

  Windows:
    
    runs-on: windows-2022

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Retrieve submodules
      run: git submodule update --init --recursive

    - name: Install Dependencies
      run: |
        Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.3.296.0/windows/VulkanSDK-1.3.296.0-Installer.exe" -OutFile VulkanSDK.exe
        # ./VulkanSDK.exe --help
        ./VulkanSDK.exe --accept-licenses --default-answer --root D:/a/VulkanSDK --confirm-command install

    - name: Prep 1
      shell: cmd
      run: | 
        cd scripts
        python gen_build.py
        python gen_distribute.py

    - name: Build Pilot Light (DEBUG)
      shell: cmd
      run: |
        set VULKAN_SDK=D:/a/VulkanSDK
        cd src
        call build.bat -c debug
        if %ERRORLEVEL% NEQ 0 exit 1
        cd ../examples
        call build.bat -c debug
        if %ERRORLEVEL% NEQ 0 exit 1

    - name: Prep 2
      shell: cmd
      run: |
        rmdir /s /q out

    - name: Build Pilot Light (DEBUG EXPERIMENTAL)
      shell: cmd
      run: |
        set VULKAN_SDK=D:/a/VulkanSDK
        cd src
        call build.bat -c debug_experimental
        if %ERRORLEVEL% NEQ 0 exit 1

    - name: Prep 3
      shell: cmd
      run: |
        rmdir /s /q out

    - name: Build Pilot Light (RELEASE EXPERIMENTAL)
      shell: cmd
      run: |
        set VULKAN_SDK=D:/a/VulkanSDK
        cd src
        call build.bat -c release_experimental
        if %ERRORLEVEL% NEQ 0 exit 1

    - name: Prep 4
      shell: cmd
      run: |
        rmdir /s /q out

    - name: Build Pilot Light (RELEASE)
      shell: cmd
      run: |
        set VULKAN_SDK=D:/a/VulkanSDK
        cd src
        call build.bat -c release
        if %ERRORLEVEL% NEQ 0 exit 1
        cd ../examples
        call build.bat -c release
        if %ERRORLEVEL% NEQ 0 exit 1

    - name: Build Pilot Light Deployment (RELEASE)
      shell: cmd
      run: |
        set VULKAN_SDK=D:/a/VulkanSDK
        cd src
        call build_distribute.bat -c release
        if %ERRORLEVEL% NEQ 0 exit 1

    - name: Package Pilot Light
      shell: cmd
      run: |
        cd $GITHUB_WORKSPACE
        cd scripts
        python package.py

    - name: Upload Pilot Light
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: pilotlight_release_win32
        path: D:\a\pilotlight\pilotlight\out\pilotlight_win32.zip
        overwrite: true

  MacOS:
    
    runs-on: macos-14

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Retrieve submodules
      run: git submodule update --init --recursive

    - name: Install Dependencies
      run: |
        curl https://sdk.lunarg.com/sdk/download/1.3.283.0/mac/vulkansdk-macos-1.3.283.0.dmg -o vk.dmg
        hdiutil attach vk.dmg
        sudo /Volumes/vulkansdk-macos-1.3.283.0/InstallVulkan.app/Contents/MacOS/InstallVulkan --root ~/VulkanSDK/1.3.283.0 --accept-licenses --default-answer --confirm-command install com.lunarg.vulkan.core com.lunarg.vulkan.usr com.lunarg.vulkan.sdl2 com.lunarg.vulkan.glm com.lunarg.vulkan.volk com.lunarg.vulkan.vma com.lunarg.vulkan.ios

    - name: Prep 1
      run: |
        cd $GITHUB_WORKSPACE
        cd scripts
        python3 gen_build.py
        python3 gen_distribute.py

    - name: Build Pilot Light (DEBUG)
      run: |
        cd $GITHUB_WORKSPACE
        cd src
        chmod +x build.sh
        ./build.sh -c debug || exit 1
        cd ../examples
        chmod +x build.sh
        ./build.sh -c debug || exit 1

    - name: Prep 2
      run: |
        cd $GITHUB_WORKSPACE
        rm -r out

    - name: Build Pilot Light (DEBUG EXPERIMENTAL)
      run: |
        cd $GITHUB_WORKSPACE
        cd src
        chmod +x build.sh
        ./build.sh -c debug_experimental || exit 1

    - name: Prep 3
      run: |
        cd $GITHUB_WORKSPACE
        rm -r out

    - name: Build Pilot Light (RELEASE EXPERIMENTAL)
      run: |
        cd $GITHUB_WORKSPACE
        cd src
        chmod +x build.sh
        ./build.sh -c release_experimental || exit 1

    - name: Prep 4
      run: |
        cd $GITHUB_WORKSPACE
        rm -r out

    - name: Build Pilot Light (RELEASE)
      run: |
        cd $GITHUB_WORKSPACE
        cd src
        chmod +x build.sh
        ./build.sh -c release || exit 1
        cd ../examples
        chmod +x build.sh
        ./build.sh -c release || exit 1

    - name: Build Pilot Light Deployment (RELEASE)
      run: |
        cd $GITHUB_WORKSPACE
        cd src
        chmod +x build_distribute.sh
        ./build_distribute.sh -c release || exit 1

    - name: Package Pilot Light
      run: |
        cd $GITHUB_WORKSPACE
        cd scripts
        python3 package.py

    - name: Upload Pilot Light
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: pilotlight_release_macos
        path: /Users/runner/work/pilotlight/pilotlight/out/pilotlight_macos.zip
        overwrite: true

  Ubuntu:
    
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Retrieve submodules
      run: git submodule update --init --recursive

    - name: Install Dependencies
      run: |
        wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.4.309-jammy.list https://packages.lunarg.com/vulkan/1.4.309/lunarg-vulkan-1.4.309-jammy.list
        sudo apt update
        sudo apt install vulkan-sdk
        sudo apt install libx11-dev
        sudo apt install libxkbcommon-x11-dev
        sudo apt install libx11-xcb-dev
        sudo apt install libxcb-xfixes0-dev
        sudo apt install libxcb-cursor-dev
        sudo apt install libxcb-cursor0
        sudo apt install libxcb-keysyms1-dev
        sudo apt install libxcursor-dev
        sudo apt install libxrandr-dev
        sudo apt install libxinerama-dev
        sudo apt install libgl-dev
        sudo apt install libxi-dev

    - name: Prep 1
      run: |
        cd $GITHUB_WORKSPACE
        cd scripts
        python3 gen_build.py
        python3 gen_distribute.py

    - name: Build Pilot Light (DEBUG)
      run: |
        cd $GITHUB_WORKSPACE
        cd src
        chmod +x build.sh
        ./build.sh -c debug || exit 1
        cd ../examples
        chmod +x build.sh
        ./build.sh -c debug || exit 1

    - name: Prep 2
      run: |
        cd $GITHUB_WORKSPACE
        rm -r out

    - name: Build Pilot Light (DEBUG EXPERIMENTAL)
      run: |
        cd $GITHUB_WORKSPACE
        cd src
        chmod +x build.sh
        ./build.sh -c debug_experimental || exit 1

    - name: Prep 3
      run: |
        cd $GITHUB_WORKSPACE
        rm -r out

    - name: Build Pilot Light (RELEASE EXPERIMENTAL)
      run: |
        cd $GITHUB_WORKSPACE
        cd src
        chmod +x build.sh
        ./build.sh -c release_experimental || exit 1

    - name: Prep 4
      run: |
        cd $GITHUB_WORKSPACE
        rm -r out

    - name: Build Pilot Light (RELEASE)
      run: |
        cd $GITHUB_WORKSPACE
        cd src
        chmod +x build.sh
        ./build.sh -c release || exit 1
        cd ../examples
        chmod +x build.sh
        ./build.sh -c release || exit 1

    - name: Build Pilot Light Deployment (RELEASE)
      run: |
        cd $GITHUB_WORKSPACE
        cd src
        chmod +x build_distribute.sh
        ./build_distribute.sh -c release || exit 1


    - name: Package Pilot Light
      run: |
        cd $GITHUB_WORKSPACE
        cd scripts
        python3 package.py
        pwd

    - name: Upload Pilot Light
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: pilotlight_release_linux
        path: /home/runner/work/pilotlight/pilotlight/out/pilotlight_linux_amd64.zip
        overwrite: true
